apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ewallet

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/faisalaffan/ewallet-system
    newTag: latest

secretGenerator:
  - name: ewallet-secrets
    envs:
      - .env
    behavior: replace
