// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/wallets": {
            "post": {
                "description": "Create wallet for an owner with a specific currency",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Create a new wallet",
                "parameters": [
                    {
                        "description": "Create wallet request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.CreateWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.Wallet"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/wallets/transfer": {
            "post": {
                "description": "Transfer funds from one wallet to another. Both must be same currency.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Transfer between wallets",
                "parameters": [
                    {
                        "description": "Transfer request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.TransferRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.TransferResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/wallets/{id}": {
            "get": {
                "description": "Retrieve wallet details including balance and status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Get wallet by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.Wallet"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/wallets/{id}/pay": {
            "post": {
                "description": "Deduct funds from wallet. Insufficient balance returns 422.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Make a payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Payment request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.PayRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.PayResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/wallets/{id}/reconcile": {
            "get": {
                "description": "Compare cached balance against SUM(ledger_entries). Returns match status and diff.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Reconcile wallet balance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.ReconcileResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/wallets/{id}/suspend": {
            "post": {
                "description": "Suspend wallet. Idempotent — already suspended returns 200.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Suspend a wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.SuspendResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    }
                }
            }
        },
        "/wallets/{id}/topup": {
            "post": {
                "description": "Add funds to wallet. Idempotent via idempotency_key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallets"
                ],
                "summary": "Top-up wallet balance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Top-up request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.TopUpRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.TopUpResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.Envelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_faisalaffan_ewallet-system_internal_domain.CreateWalletRequest": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_internal_domain.PayRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_internal_domain.PayResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "string"
                },
                "entry_id": {
                    "type": "string"
                },
                "wallet_id": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_internal_domain.ReconcileResponse": {
            "type": "object",
            "properties": {
                "cached_balance": {
                    "type": "string"
                },
                "diff": {
                    "type": "string"
                },
                "ledger_sum": {
                    "type": "string"
                },
                "match": {
                    "type": "boolean"
                },
                "wallet_id": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_internal_domain.SuspendResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.WalletStatus"
                },
                "wallet_id": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_internal_domain.TopUpRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_internal_domain.TopUpResponse": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "string"
                },
                "entry_id": {
                    "type": "string"
                },
                "wallet_id": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_internal_domain.TransferRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "from_wallet_id": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "to_wallet_id": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_internal_domain.TransferResponse": {
            "type": "object",
            "properties": {
                "from_balance": {
                    "type": "string"
                },
                "to_balance": {
                    "type": "string"
                },
                "transfer_id": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_internal_domain.Wallet": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_internal_domain.WalletStatus"
                },
                "updated_at": {
                    "type": "string"
                },
                "wallet_id": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_internal_domain.WalletStatus": {
            "type": "string",
            "enum": [
                "ACTIVE",
                "SUSPENDED"
            ],
            "x-enum-varnames": [
                "WalletStatusActive",
                "WalletStatusSuspended"
            ]
        },
        "github_com_faisalaffan_ewallet-system_pkg_response.Envelope": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.apiError"
                },
                "pagination": {
                    "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.pagination"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_pkg_response.ValidationDetail": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_pkg_response.apiError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_faisalaffan_ewallet-system_pkg_response.ValidationDetail"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_faisalaffan_ewallet-system_pkg_response.pagination": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Multi-Currency E-Wallet API",
	Description:      "Ledger-based e-wallet backend with multi-currency support.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
